// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingApp.Data;

#nullable disable

namespace ShippingApp.Migrations
{
    [DbContext(typeof(shipmentAppDatabase))]
    [Migration("20230413085835_shipmentRoute2")]
    partial class shipmentRoute2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShippingApp.Models.CheckpointModel", b =>
                {
                    b.Property<Guid>("checkpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("checkpointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("latitude")
                        .HasColumnType("real");

                    b.Property<float>("longitude")
                        .HasColumnType("real");

                    b.HasKey("checkpointId");

                    b.ToTable("Checkpoint");
                });

            modelBuilder.Entity("ShippingApp.Models.CheckpointsDistanceModel", b =>
                {
                    b.Property<Guid>("distancMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("checkpoint1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("checkpoint2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("cost")
                        .HasColumnType("real");

                    b.Property<float>("distance")
                        .HasColumnType("real");

                    b.HasKey("distancMapId");

                    b.ToTable("CheckpointMappings");
                });

            modelBuilder.Entity("ShippingApp.Models.ShipmentModel", b =>
                {
                    b.Property<Guid>("shipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cointainerTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("customerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dateOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("productTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("shipmentPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("shipmentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("shipmentWeight")
                        .HasColumnType("real");

                    b.HasKey("shipmentId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShippingApp.Models.ShipmentStatusModel", b =>
                {
                    b.Property<Guid>("shipmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("currentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("shipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("shipmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shipmentStatusId");

                    b.ToTable("ShipmentStatus");
                });

            modelBuilder.Entity("ShippingApp.Models.test", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("tests");
                });
#pragma warning restore 612, 618
        }
    }
}
